config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  # TOPページ
  get "/", {
    :to => "top#index",
    :as => "top",
  }

  # ----------------------------------------------
  # api
  # ----------------------------------------------
  namespace "api" do

    # 画像を取り扱うAPI
    scope "image" do

      # ログインユーザーがアップ済みの画像一覧を取得する
      get "/list", {
        :to => "images#list",
        :as => "images_owner_has",
      }
      # 指定した異性ユーザーの全画像を取得する
      get "/list/:member_id", {
        :to => "images#member",
        :as => "images_selected_member_has",
      }
      # 画像表示用 URL(※所有者のみ閲覧可能)
      get "/:id/:member_id/:token_for_api", {
        :to => "images#owner_image_url",
        :as => "private_image",
      }
      # 画像表示用 URL(※第三者閲覧用)
      get "/:id/:token", {
        :to => "images#image_url",
        :as => "public_image",
      }
      # To upload any images.
      post "/update/:id", {
        :to => "images#update",
        :as => "image_update",
      }
      post "/delete/:id", {
        :to => "images#delete",
        :as => "image_delete",
      }
      post "/", {
        :to => "images#upload",
        :as => "image_upload",
      }
    end

    # メッセージ送信用
    scope "timeline" do
      get "/messages/:from_member_id/:to_member_id", {
        :to => "timelines#messages",
        :as => "timeline_messages",
      }
      post "/", {
        :to => "timelines#create_message",
        :as => "timeline_create_message",
      }
      post "/upload", {
        :to => "timelines#create_image",
        :as => "timeline_create_image",
      }
    end

    # API用ユーティリティー情報
    scope "utilities" do
      get "/get", {
        :to => "utilities#get",
        :as => "utilities_list",
      }
    end

    # メンバー情報を取得するためのAPI
    scope "member" do
      get "/:id", {
        :to => "member#show",
        :as => "member_show",
      }
    end
  end

  get "sessions/new"
  resources :logs
  resources :urls
  resources :declines
  # resources :images
  # resources :messages
  # resources :timelines
  resources :footprints
  # resources :likes
  # resources :members
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ----------------------------------------------
  # 通常のHTTPリクエスト
  # List notices to logged in user.
  # ----------------------------------------------
  get "/notices/", {
    :to => "notices#index",
    :as => "notices",
  }

  post "/images/active/:id", {
    :to => "images#active",
    :as => "active_image",
  }

  post "/images/deactive/:id", {
    :to => "images#deactive",
    :as => "deactive_image",
  }

  # ----------------------------------------------
  # メッセージ
  # ----------------------------------------------
  get "/messages/", {
    :to => "messages#index",
    :as => "messages",
  }
  get "/messages/:id", {
    :to => "messages#talk",
    :as => "message_talk",
  }
  post "/messages/create", {
    :to => "messages#create",
    :as => "message_create",
  }

  # ----------------------------------------------
  # いいねを贈る
  # ----------------------------------------------
  # 異性にいいねを贈る
  post "/like/send/:id", {
    :to => "likes#inform",
    :as => "inform_like",
  }
  # 贈ったいいねをキャンセル
  post "/like/cancel/:id", {
    :to => "likes#cancel",
    :as => "cancel_like",
  }

  # ----------------------------------------------
  # マイページ関連
  # ----------------------------------------------
  get "/mypage", {
    :to => "mypage#index",
    :as => "mypage",
  }
  get "/mypage/edit", { :to => "mypage#edit" }
  patch "/mypage/edit", { :to => "mypage#update" }
  # 画像のぼかし具合を設定
  post "/mypage/upload/:id", {
    :to => "mypage#update_image",
    :as => "mypage_update_image",
  }
  get "/mypage/upload", {
    :to => "mypage#upload",
  }
  post "/mypage/upload", { :to => "mypage#completed_uploading" }
  delete "/mypage/delete_image", {
    :to => "mypage#delete_image",
  }

  # 贈ったいいね
  get "/mypage/informing_likes", {
        :to => "mypage#informing_likes",
        :as => "mypage_informing_likes",
      }
  # もらったいいね
  get "/mypage/getting_likes", {
        :to => "mypage#getting_likes",
        :as => "mypage_getting_likes",
      }
  # マッチング中ユーザー一覧
  get "/mypage/matching", {
    :to => "mypage#matching",
    :as => "mypage_matching",
  }
  # ブロック中ユーザー一覧
  get "/mypage/blocking", {
    :to => "mypage#blocking",
    :as => "mypage_blocking",
  }
  # 足跡一覧
  get "/mypage/footprints", {
    :to => "mypage#footprints",
    :as => "mypage_footprints",
  }
  # # ログ一覧
  # get "/mypage/logs", {
  #   :to => "mypage#logs",
  #   :as => "mypage_logs",
  # }
  get "/mypage/logout", {
    :to => "mypage#logout",
    :as => "logout",
  }
  # ログイン中ユーザーが自身のプロフィール画面を閲覧する
  get "/mypage/profile", :to => "mypage#prfile", :as => "mypage_profile"

  # ----------------------------------------------
  # ログインページ
  # ----------------------------------------------
  scope "login", :as => :login do
    get "/", {
      :to => "sessions#new",
    }
    post "/", {
      :to => "sessions#create",
    }
  end

  # ----------------------------------------------
  # 新規登録時の仮登録
  # ----------------------------------------------
  scope("register", :as => :register) do
    post "/", {
      :to => "register#create",
      :as => "create",
    }
    get "/", {
      :to => "register#index",
      :as => "index",
    }
    get "/:id/:token", {
      :to => "register#main_index",
      :as => "main_index",
    }
    post "/:id/:token", {
      :to => "register#main_create",
      :as => "main_create",
    }
    get "/completed", {
      :to => "register#completed",
      :as => "completed",
    }
    get "/pre-completed", {
      :to => "register#completed",
      :as => "pre-completed",
    }
  end

  # ----------------------------------------------
  # メンバー情報関連
  # ----------------------------------------------
  scope "members", :as => :members do
    get "/search", {
      :to => "members#search",
      :as => "search",
    }
    get "/:id", {
      :to => "members#show",
      :as => "show",
    }
    get "/", {
      :to => "members#index",
      :as => "index",
    }
  end
end

app/models/message.rb
class Message < ApplicationRecord

  # メッセージの入力内容のバリデーション
  validates :message, {
    :presence => {
      :message => "メッセージは必須項目です",
    },
    :length => {
      :minumum => 1,
      :maximum => 1024,
    },
  }

  # 発言者member_idのバリデーション
  validates :member_id, {
    :presence => {
      :message => "発言者member_idは必須項目です",
    },
  # :inclusion => {
  #   :in => self.registered_members,
  # },
  }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # 現時点で､メッセージ可能なメンバーリストを表示
  def index
    @matching_members = @current_user.matching_members(@current_user.id, @current_user.forbidden_members).to_a.map do |member|
      next member.id
    end

    @members = Member.select([
      :id,
      :display_name,
      "max(timelines.created_at) as timeline_created_at",
    ]).where({
      :id => @matching_members,
    }).joins(%{LEFT JOIN timelines on timelines.from_member_id = members.id and timelines.to_member_id = #{@current_user.id}})
      .group([
        :id,
        :display_name,
      ]).order("timeline_created_at desc nulls last")

    return render :template => "messages/index"
  end

  def talk
    @matching_members = @current_user.matching_members(@current_user.id, @current_user.forbidden_members).map do |member|
      next member.id
    end
    if @matching_members.include?(params[:id].to_i) != true
      raise StandardError.new "メッセージ相手が見つかりませんでした"
    end

    # メッセージ相手のメンバー情報
    @opponent = Member.find(params[:id])
    if @opponent == nil
      raise StandardError.new "メッセージ相手が見つかりませんでした"
    end

    # 現時点までの､メッセージのやり取りデータを取得する
    @timeline_id_list = Timeline.where({
      :from_member_id => @current_user.id,
      :to_member_id => params[:id],
    }).or(
      Timeline.where({
        :from_member_id => params[:id],
        :to_member_id => @current_user.id,
      })
    ).to_a.map do |timeline|
      next timeline.id
    end

    # 閲覧中のメンバー同士の発言のみを取得
    @to_member_id = params[:id]

    @timelines = Timeline.where({
      :id => @timeline_id_list,
    }).order(
      :created_at => :desc,
    ).limit(10)

    @timelines = @timelines.sort do |a, b|
      a.id <=> b.id
    end

    pp @timelines
    # 任意のテンプレート
    return render :template => "messages/talk"
  rescue => error
    return render :template => "errors/index"
  end

  # 入力内容をレコードに新規追加する
  def create
    params.fetch(:message, {}).permit(
      :from_member_id,
      :to_member_id,
      :message
    )
    @message = Message.new({
      :member_id => @current_user.id,
      :message => params[:message][:message],
    })

    if @message.validate() != true
      raise StandardError.new "メッセージを送信できませんでした"
    end

    response = @message.save()

    @timeline = Timeline.new({
      :from_member_id => @current_user.id,
      :to_member_id => params[:message][:to_member_id],
      :message_id => @message.id,
    })

    if @timeline.validate() != true
      raise StandardError.new "タイムラインの保存に失敗しました"
    end

    @timeline.save()

    return redirect_to(message_talk_url :id => params[:message][:to_member_id])
  rescue => exception
    logger.info exception
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.fetch(:message, {})
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<a href="" class="backk">戻る</a>
<section>
  <% if @members.length > 0 %>
    <div class="box">
      <% @members.each do |member| %>
        <a href="<%= message_talk_url :id => member.id  %>" class="message_list">
          <div class="message_list1">
            <% if member.showable_images.length > 0 %>
              <img src="<%= member.showable_images.first.image_url() %>">
            <% else %>
              <img src="/images/sample_user.jpg">
            <% end %>
          </div>
          <div class="message_list2">
            <% if member.timeline_created_at != nil then %>
              <p><%= member.timeline_created_at.strftime("%Y年%m月%d日 %H時%M分%S秒") %></p>
              <p><%= member.display_name %>さんからメッセージを受信しました</p>
            <% else %>
              <p><%= member.display_name %>さん</p>
              <p>まだメッセージのやり取りがありません</p>
            <% end %>
          </div>
        </a>
      <% end %>
    </div>
  <% else %>
    <div class="box">
      <h2 class="noto">メッセージ</h2>
      <p class="cation">現在､メッセージのやり取りが可能なマッチング済みのユーザーはいません｡</p>
      <div class="tex_c">
        <p class="font12">
          <a class="button_to_back_previous_page" href="{{url()->previous()}}">前ページへ戻る</a>
        </p>
      </div>
    </div>
  <% end %>
</section>
<!-- ページング機能 -->
@if ($matching_users->hasPages())
<div class="paging">
  {{-- Previous Page Link --}}
  @if ($matching_users->onFirstPage())
  {{-- <span class="disabled" aria-disabled="true">
    <img src="/images/back.png" width="24">
  </span> --}}
  @else
  <a href="{{ $matching_users->previousPageUrl() }}" rel="prev">
    <img src="/images/back.png" width="24">
  </a>
  @endif
  {{-- Next Page Link --}}
  @if ($matching_users->hasMorePages())
  <a href="{{ $matching_users->nextPageUrl() }}" rel="next">
    <img src="/images/forward.png" width="24">
  </a>
  @else
  {{-- <span class="disabled" aria-disabled="true">
    <img src="/images/forward.png" width="24">
  </span> --}}
  @endif
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/messages/talk.html.erb
<a href="" class="backk">戻る</a>
<div id="chat_area">
  <section>
    <div class="message_face">
      <% if @opponent.showable_images.length > 0 then %>
        <a href="">
          <img src="<%= @opponent.showable_images.first.image_url() %>">
        </a>
      <% else %>
        <a href="">
          <img src="/images/sample_user.jpg">
        </a>
      <% end %>
    </div>
    <p><%= @opponent.display_name %></p>
    <div class="talk">
      <p v-on:click="fetchPastTimelines" class="past_message_btn">過去のメッセージを取得</p>
      <!-- メッセージのループ -->
      <div v-for="timeline in timelines">
        <div class="talkin_r" v-if="timeline.from_member_id == fromMemberId.value">
          <p class="kidokuornot">{{timeline.browsed}}</p>
          <div v-if="timeline.message != null" class="balloon1-right">
            <p>{{timeline.message.message}}</p>
          </div>
          <div v-if="timeline.image != null" class="balloon1-right-img">
            <p>
              <a target="_blank" >
                <img v-bind:src="timeline.image.image_url" width="100" >
              </a>
            </p>
            <p class="kidokuornot">{{timeline.created_at_string}}</p>
          </div>
          <!-- URLリンクが送信された場合 -->
          <div v-if="timeline.url != null" class="balloon1-right">
            <p><a v-bind:href="timeline.url.url" target="_blank">{{timeline.url.url}}</a></p>
          </div>
        </div>
        <div v-else class="talkin_l">
          <div v-if="timeline.message != null" class="balloon1-left">
            <p>{{timeline.message.message}}</p>
          </div>
          <div v-if="timeline.image != null" class="balloon1-left-img">
            <p>
              <a target="_blank" >
                <img v-bind:src="timeline.image.image_url" width="100" >
              </a>
            </p>
          </div>
        </div>
      </div>
      <div class="prepare_uploading_image">
        <img v-bind:src="file_resorce" id="selected_image">
        <input type="hidden" id="url-to-upload-image" name="urlToUploadImage" value="<%= api_image_upload_path() %>">
        <input type="hidden" name="member_id" value="<%= @current_user.id %>">
        <input type="hidden" name="member_id" value="<%= @current_user.token_for_api %>">
        <input type="file"   name="upload_file" v-on:change="selectFile($event)">
        <input type="submit" name="submit" v-on:click="uploadSelectedFile" id="button-to-upload-image" value="ファイルをアップロード">
      </div>
    </div>
    <%= form_for :message, :url => api_timeline_create_message_path, :method => "post", :html => {:id => "send-message-form"} do |form| %>
      <%= form.hidden_field :request_url, :value => api_timeline_create_message_path(), :ref => "requestUrl" %>
      <%= form.hidden_field :from_member_id, :value => @current_user.id, :ref => "fromMemberId" %>
      <%= form.hidden_field :to_member_id, :value => @to_member_id, :ref => "toMemberId" %>
      <%= form.hidden_field :token_for_api, :value => @current_user.token_for_api, :ref => "tokenForApi" %>
      <%= form.hidden_field :api_timeline_messages, :value => api_timeline_messages_path(:from_member_id => @current_user.id, :to_member_id => @to_member_id), :ref => "apiTimelineMessagesUrl" %>
      <p><%= form.submit "submit-to-create-message", :id => "send-message", :"v-on:click" => "sendMessage($event)", :value => "メッセージ送信" %></p>
      <p><%= form.text_field :message, :placeholder => "※メッセージを入力して下さい", :ref => "message" %></p>
    <% end %>
  </section>
  <!--
  <div class="talk_form">
    <div class="talk_form2">
    </div>
  </div>
  -->
</div>
<script src="https://unpkg.com/vue@next"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  {
    let app = Vue.createApp({
      data: function () {
        return {
          timelines: [],
          limit: 10,
          offset: 0,
          selected_file: null,
          file_binary: null,
          file_resorce: null,
        }
      },
      setup: function () {
        return {
          fromMemberId: Vue.ref(0),
          toMemberId: Vue.ref(0),
          tokenForApi: Vue.ref(""),
          requestUrl: Vue.ref(""),
          message: Vue.ref(""),
          apiTimelineMessagesUrl: Vue.ref(""),
        }
      },
      mounted: function () {
        console.log(Vue.toRaw(this.timelines));
        this.fetchTimelines();
      },
      methods: {
        fetchTimelines: function () {
          let options = {
            headers: {
              member_id: this.fromMemberId.value,
              token_for_api: this.tokenForApi.value,
            }
          }
          let url = this.apiTimelineMessagesUrl.value
          url += "?offset=" + this.offset + "&limit=10";
          axios.get(url, options).then((response) => {
            console.log("fetchTimelines");
            console.log(response);
            if (response.data.status === true) {
              this.timelines = response.data.response
            }
          });
        },
        // 過去のメッセージリストを取得
        fetchPastTimelines: function () {
          this.offset += 10
          let options = {
            headers: {
              member_id: this.fromMemberId.value,
              token_for_api: this.tokenForApi.value,
            }
          }
          let url = this.apiTimelineMessagesUrl.value;
          url += "?offset=" + this.offset + "&limit=10";
          axios.get(url, options).then((response) => {
            if (response.data.status) {
              let timelines = response.data.response.concat(Vue.toRaw(this.timelines));
              this.timelines = timelines;
              return true;
            } else {
              return false
            }

            // console.log("=====================================>>")
            // console.log(response);
            // console.log(this.timelines);
            // this.timelines = this.timelines.splice(0, 0, response.data.response)
            // console.log(this.timelines);

            // this.timelines.concat(response.data.response);
            // this.timelines = response.data.concat(this.timelines)
          });
        },
        sendMessage: function(event) {
          event.preventDefault();
          let postData = {
            message: {
              from_member_id: this.fromMemberId.value,
              to_member_id: this.toMemberId.value,
              token_for_api: this.tokenForApi.value,
              message: this.message.value,
            }
          }
          let options = {
            headers: {
              "token_for_api": this.tokenForApi,
              "member_id": this.fromMemberId,
            }
          }
          axios.post(this.requestUrl.value, postData, options).then((response) => {
            if (response.data.status === true) {
              let timelines = response.data.response.timelines;
              timelines.forEach((timeline) => {
                this.timelines.push(timeline);
              });
              this.message.value = "";
            } else {
              console.log(response.data.response);
              throw new Error(response.data.response)
            }
          }).catch((error) => {
            console.log(error);
            // alert(error);
          });
        },
        selectFile: function (event) {
          let files = event.target.files
          let reader = new FileReader();
          let file_binary = null;
          this.file_binary = files[0];
          reader.onload = (e) => {
            // console.log(e);
            console.log(e)
            alert(e.target.result)
            // console.log(reader.result);
            this.file_resorce = URL.createObjectURL(files[0]);
          }
          reader.readAsBinaryString(files[0])

          console.log(files);
        },
        uploadSelectedFile: function() {
          let options = {
            headers: {
              member_id: this.fromMemberId.value,
              token_for_api: this.tokenForApi.value,
            }
          }
          let postData = new FormData();
          postData.append("image[upload_file]", this.file_binary)
          postData.append("image[from_member_id]", this.fromMemberId.value)
          postData.append("image[to_member_id]", this.toMemberId.value)
          // Request with post.
          axios.post("/api/timeline/upload", postData, options).then((response) => {
            console.log("ファイルアップロード成功");
            console.log(response)
            if (response.data.status === true) {
              this.timelines.push(response.data.response.timeline);
              this.file_resorce = null;
            }
          })
        }
      }
    })
    const vm = app.mount("#chat_area");
  }
</script>