config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  # TOPページ
  get "/", {
    :to => "top#index",
    :as => "top",
  }

  # ----------------------------------------------
  # api
  # ----------------------------------------------
  namespace "api" do

    # 画像を取り扱うAPI
    scope "image" do

      # ログインユーザーがアップ済みの画像一覧を取得する
      get "/list", {
        :to => "images#list",
        :as => "images_owner_has",
      }
      # 指定した異性ユーザーの全画像を取得する
      get "/list/:member_id", {
        :to => "images#member",
        :as => "images_selected_member_has",
      }
      # 画像表示用 URL(※所有者のみ閲覧可能)
      get "/:id/:member_id/:token_for_api", {
        :to => "images#owner_image_url",
        :as => "private_image",
      }
      # 画像表示用 URL(※第三者閲覧用)
      get "/:id/:token", {
        :to => "images#image_url",
        :as => "public_image",
      }
      # To upload any images.
      post "/update/:id", {
        :to => "images#update",
        :as => "image_update",
      }
      post "/delete/:id", {
        :to => "images#delete",
        :as => "image_delete",
      }
      post "/", {
        :to => "images#upload",
        :as => "image_upload",
      }
    end

    # メッセージ送信用
    scope "timeline" do
      get "/messages/:from_member_id/:to_member_id", {
        :to => "timelines#messages",
        :as => "timeline_messages",
      }
      post "/", {
        :to => "timelines#create_message",
        :as => "timeline_create_message",
      }
      post "/upload", {
        :to => "timelines#create_image",
        :as => "timeline_create_image",
      }
    end

    # API用ユーティリティー情報
    scope "utilities" do
      get "/get", {
        :to => "utilities#get",
        :as => "utilities_list",
      }
    end

    # メンバー情報を取得するためのAPI
    scope "member" do
      get "/:id", {
        :to => "member#show",
        :as => "member_show",
      }
    end
  end

  get "sessions/new"
  resources :logs
  resources :urls
  resources :declines
  # resources :images
  # resources :messages
  # resources :timelines
  resources :footprints
  # resources :likes
  # resources :members
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ----------------------------------------------
  # 通常のHTTPリクエスト
  # List notices to logged in user.
  # ----------------------------------------------
  get "/notices/", {
    :to => "notices#index",
    :as => "notices",
  }

  post "/images/active/:id", {
    :to => "images#active",
    :as => "active_image",
  }

  post "/images/deactive/:id", {
    :to => "images#deactive",
    :as => "deactive_image",
  }

  # ----------------------------------------------
  # メッセージ
  # ----------------------------------------------
  get "/messages/", {
    :to => "messages#index",
    :as => "messages",
  }
  get "/messages/:id", {
    :to => "messages#talk",
    :as => "message_talk",
  }
  post "/messages/create", {
    :to => "messages#create",
    :as => "message_create",
  }

  # ----------------------------------------------
  # いいねを贈る
  # ----------------------------------------------
  # 異性にいいねを贈る
  post "/like/send/:id", {
    :to => "likes#inform",
    :as => "inform_like",
  }
  # 贈ったいいねをキャンセル
  post "/like/cancel/:id", {
    :to => "likes#cancel",
    :as => "cancel_like",
  }

  # ----------------------------------------------
  # マイページ関連
  # ----------------------------------------------
  get "/mypage", {
    :to => "mypage#index",
    :as => "mypage",
  }
  get "/mypage/edit", { :to => "mypage#edit" }
  patch "/mypage/edit", { :to => "mypage#update" }
  # 画像のぼかし具合を設定
  post "/mypage/upload/:id", {
    :to => "mypage#update_image",
    :as => "mypage_update_image",
  }
  get "/mypage/upload", {
    :to => "mypage#upload",
  }
  post "/mypage/upload", { :to => "mypage#completed_uploading" }
  delete "/mypage/delete_image", {
    :to => "mypage#delete_image",
  }

  # 贈ったいいね
  get "/mypage/informing_likes", {
        :to => "mypage#informing_likes",
        :as => "mypage_informing_likes",
      }
  # もらったいいね
  get "/mypage/getting_likes", {
        :to => "mypage#getting_likes",
        :as => "mypage_getting_likes",
      }
  # マッチング中ユーザー一覧
  get "/mypage/matching", {
    :to => "mypage#matching",
    :as => "mypage_matching",
  }
  # ブロック中ユーザー一覧
  get "/mypage/blocking", {
    :to => "mypage#blocking",
    :as => "mypage_blocking",
  }
  # 足跡一覧
  get "/mypage/footprints", {
    :to => "mypage#footprints",
    :as => "mypage_footprints",
  }
  # # ログ一覧
  # get "/mypage/logs", {
  #   :to => "mypage#logs",
  #   :as => "mypage_logs",
  # }
  get "/mypage/logout", {
    :to => "mypage#logout",
    :as => "logout",
  }
  # ログイン中ユーザーが自身のプロフィール画面を閲覧する
  get "/mypage/profile", :to => "mypage#prfile", :as => "mypage_profile"

  # ----------------------------------------------
  # ログインページ
  # ----------------------------------------------
  scope "login", :as => :login do
    get "/", {
      :to => "sessions#new",
    }
    post "/", {
      :to => "sessions#create",
    }
  end

  # ----------------------------------------------
  # 新規登録時の仮登録
  # ----------------------------------------------
  scope("register", :as => :register) do
    post "/", {
      :to => "register#create",
      :as => "create",
    }
    get "/", {
      :to => "register#index",
      :as => "index",
    }
    get "/:id/:token", {
      :to => "register#main_index",
      :as => "main_index",
    }
    post "/:id/:token", {
      :to => "register#main_create",
      :as => "main_create",
    }
    get "/completed", {
      :to => "register#completed",
      :as => "completed",
    }
    get "/pre-completed", {
      :to => "register#completed",
      :as => "pre-completed",
    }
  end

  # ----------------------------------------------
  # メンバー情報関連
  # ----------------------------------------------
  scope "members", :as => :members do
    get "/search", {
      :to => "members#search",
      :as => "search",
    }
    get "/:id", {
      :to => "members#show",
      :as => "show",
    }
    get "/", {
      :to => "members#index",
      :as => "index",
    }
  end
end

app/models/register.rb
# 仮登録処理用のモデルクラス
class Register < ApplicationRecord
  self.table_name = "members"

  # 任意の処理で指定のカラムをバリデーションする
  validates_each :email do |object, attr, value|
    # メールアドレスがすべて小文字かどかを判定
    if value.downcase != value
      object.errors.add(attr, "メールアドレスはすべて小文字で入力してください")
      next false
    end
    member = self.find_by({
      :email => value,
      :is_registered => UtilitiesController::BINARY_TYPE[:on],
    })

    # 既に本登録完了済みのメールアドレスの場合はエラーメッセージを追加する
    if member != nil
      object.errors.add(attr, "このメールアドレスは使用できません")
      next false
    end
    next true
  end

  # emailバリデーション
  validates(:email, {
    :presence => {
      :message => "メールアドレスは必須項目です",
    },
    :length => {
      :minimum => 5,
      :maximum => 512,
      :message => "メールアドレスは1文字以上512文字以内で入力して下さい",
    },
  })

  # display_name(本名とは違うニックネーム表示用)
  validates :display_name, {
    :presence => {
      :message => "ニックネームは必須項目です",
    },
    :length => {
      :minimum => 1,
      :maximum => 128,
      :message => "ニックネームは5文字以上128文字以内で入力して下さい",
    },
  }

  # 性別
  validates :gender, {
    :presence => true,
    :length => {
      :minimum => 1,
    },
    :inclusion => {
      # mapメソッドで1以上の値で構成された配列を返却する
      :in => UtilitiesController.gender_id_list.map do |gender|
        if gender > 0
          next gender
        end
      end,
      :message => "性別は未設定以外を選択して下さい",
    },
  }
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  before_action :set_register, only: %i[ show edit update destroy ]
  before_action :set_member, only: %i[ main_create ]

  def index
    @register = Register.new
    render ({
      :template => "register/index",
    })
  end

  # -----------------------------------------
  # 仮登録処理の実行
  # -----------------------------------------
  def create
    # 本登録用トークンを生成
    token = TokenForApi.make_random_token(128)
    logger.info "新規で生成されたトークン #{token}"

    # 重複仮登録の場合を検証
    @register = Register.find_by({
      :email => register_params[:email],
      :is_registered => UtilitiesController::BINARY_TYPE[:off],
    })

    update_params = register_params.to_hash
    update_params["token"] = token

    completed = false
    if @register != nil
      response = @register.update(update_params)
      completed = true
    else
      @register = Register.new(update_params)
      if @register.validate && @register.save!
        completed = true
      end
    end

    if completed == true
      return render :template => "register/completed"
    end
    # エラー時
    return render ({ :template => "register/index" })
  rescue => exception
    logger.info exception
    return render :template => "errors/index"
  end

  # -----------------------------------------
  # 本登録処理初期表示
  # -----------------------------------------
  def main_index
    # 仮登録ユーザーの存在チェック
    @member = Member.find_by({
      :id => params[:id],
      :token => params[:token],
      :is_registered => UtilitiesController::BINARY_TYPE[:off],
    })

    # 仮登録中ユーザーが存在する場合
    if @member != nil
      return render ({ :template => "register/main_index" })
    else
      return render :template => "register/error"
    end
  rescue => error
    logger.info error
    return render :template => "errors/index"
  end

  # -----------------------------------------
  # 本登録処実行処理
  # -----------------------------------------
  def main_create
    # memberオブジェクトの作成
    @member = Member.new(member_params)
    if @member.validate() != true
      raise ActiveModel::ValidationError.new @member
    end

    # memberオブジェクトの再取得
    @member = Member.find_by({
      :id => member_params[:id],
      :token => member_params[:token],
      :is_registered => UtilitiesController::BINARY_TYPE[:off],
    })
    if (@member == nil)
      raise StandardError.new("仮登録中ユーザーが見つかりませんでした")
    end

    # postデータをHashオブジェクトに
    member_params_hash = member_params.to_hash()
    member_params_hash["is_registered"] = Constants::Binary::Type[:on]
    member_params_hash["token_for_api"] = TokenForApi::make_random_token(128)

    # updateメソッドが成功した場合
    if @member.update(member_params_hash) != true
      raise StandardError.new("本登録処理に失敗しました")
    end

    # ログインページにリダイレクト
    return(redirect_to(login_url))
  rescue ActiveModel::ValidationError => error
    # モデル内Errorの取得
    logger.info error.model.errors.messages
    return render({ :template => "register/main_index" })
  rescue => exception
    logger.info exception
    return render({ :template => "register/main_index" })
  end

  # ログインチェックをoverride
  def login_check
    return true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_register
    @register = Register.find(params[:id])
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def register_params
    params.fetch(:register, {})
      .permit(
        :id,
        :email,
        :display_name,
        :family_name,
        :given_name,
        :gender,
        :height,
        :weight,
        :birthday,
        :salary,
        :message,
        :memo,
        :is_registered,
        :password,
        :password_confirmation,
        :password_digest,
        :token,
        :native_language,
      )
  end

  def member_params
    params.fetch(:member, {})
      .permit(
        :id,
        :email,
        :display_name,
        :family_name,
        :given_name,
        :gender,
        :height,
        :weight,
        :birthday,
        :salary,
        :message,
        :memo,
        :is_registered,
        :password,
        :password_confirmation,
        :password_digest,
        :token,
        :native_language,
        :agree,
      )
  end
end

app/helpers/register_helper.rb
module RegisterHelper

  # ランダムなトークンを作成する
  def make_random_token(size = 64)

    # トークンの最大長は最低16文字とする
    if size < 16
      size = 16
    end

    # 返却するトークン
    token = ""
    # 有効な文字群
    characters = []

    # 小文字のアルファベット
    small_alphabets = ("a".."z").to_a

    # 大文字のアルファベット
    big_alphabets = ("A".."Z").to_a
    # 数字
    numbers = (0..9).to_a

    characters = small_alphabets + big_alphabets + numbers

    characters.push("_").push("-").push("$")
    # p "charcters =====>", characters
    # 有効な文字群の長さ
    char_length = characters.length - 1
    # p char_length
    size.times do |index|
      random_index = rand(0..char_length)
      # p "radon_index ----->", random_index
      token += characters[random_index].to_s
    end

    return(token)
  end
end

app/views/register/_form.html.erb
<section>
  <div class="box">
    <h2>会員登録</h2>
    <%= form_with :url => register_main_create_path, :model => member, :method=>  "post"  do |form| %>
      <!-- 仮登録時のトークン -->
      <%= form.hidden_field :token %>
      <%= form.hidden_field :id, :value => member.id %>
      <!-- メールアドレス -->
      <p>メールアドレス</p>
      <% if (member.errors.messages.length > 0) then %>
        <% member.errors.messages[:email].each do |error| %>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <%= form.text_field :email, :readonly => true %>
      <!-- パスワード -->
      <p>パスワード</p>
      <% if member.errors.messages.length > 0 then%>
        <% member.errors.messages[:password].each do |error| %>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <%= form.text_field :password, {:placeholder => "パスワード"} %>
      <p>確認用パスワード</p>
      <% if member.errors.messages.length > 0 then%>
        <% member.errors.messages[:password_confirmation].each do |error| %>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <%= form.text_field :password_confirmation, {:placeholder => "確認用パスワード"} %>
      <!--- ユーザー名 -->
      <p>ユーザー名</p>
      <% if member.errors.messages.length > 0 then %>
        <% member.errors.messages[:display_name].each do |error|%>
          <p class="input_red"><%= error %></p>
        <%end%>
      <%end%>
      <%= form.text_field :display_name, :placeholder => "ユーザー名" %>
      <!--- 姓 -->
      <p>姓</p>
      <% if member.errors.messages.length > 0 then %>
        <% member.errors.messages[:family_name].each do |error|%>
          <p class="input_red"><%= error %></p>
        <%end%>
      <%end%>
      <%= form.text_field :family_name, :placeholder => "姓" %>
      <!--- 名 -->
      <p>名</p>
      <% if member.errors.messages.length > 0 then %>
        <% member.errors.messages[:given_name].each do |error|%>
          <p class="input_red"><%= error %></p>
        <%end%>
      <%end%>
      <%= form.text_field :given_name, :placeholder => "名" %>
      <!-- 性別 -->
      <% if member.errors.messages.length > 0 then %>
        <% member.errors.messages[:gender].each do |error|%>
          <p class="input_red"><%= error %></p>
        <%end%>
      <%end%>
      <div class="selectors">
        <p>性別</p>
        <div class="cp_ipselect cp_sl04">
          <%= form.select :gender, @genders %>
        </div>
      </div>
      <!-- 母国語の設定 -->
      <% if member.errors.messages.length > 0 then %>
        <% member.errors.messages[:native_language].each do |error|%>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <div class="selectors">
        <p>母国語</p>
        <div class="cp_ipselect cp_sl04">
          <%= form.select :native_language, @languages %>
        </div>
      </div>
      <!--selectors-->
      <div class="selectors mb32">
        <p>通知の設定</p>
        <label>
          {{Form::checkbox("notification_good", 1, old("notification_good"))}} Goodを受信時メール
        </label><br>
        <label>
          {{Form::checkbox("notification_message", 1, old("notification_message"))}} メッセージを受信時メール
        </label>
      </div>
      <!--selectors-->
      <div class="selectors mb32">
        <p>利用規約の同意</p>
        <p>※本サービス利用については以下､利用規約に同意する必要があります｡</p>
        <p><a target="_blank" href="/terms">利用規約</a></p>
        <% if member.errors.messages.length > 0 %>
          <% member.errors.messages[:agree].each do |error|%>
            <p class="input_red"><%= error %></p>
          <% end %>
        <% end %>
        <label>
          <% if member.agree.to_i == 1 %>
            <%= form.check_box :agree, {:checked => true, :include_hidden => false}, 1 %>利用規約に同意する
          <% else %>
            <%= form.check_box :agree, {:checked => false, :include_hidden => false}, 1 %>利用規約に同意する
          <% end %>
        </label>
      </div>
      <!--selectors-->
      <div class="btnbox">
        <a class="submit_button btn">登録してはじめる</a>
      </div>
    <% end %>
  </div>
  <!--box-->
</section>
<script>
  $(function () {
      // フォームの投稿ボタン
      $(".submit_button").on("click", function (e) {
          // 年月日を生年月日にフォーマットさせる。
          var year = $("select[name=year]").val();
          var month = $("select[name=month]").val();
          var day = $("select[name=day]").val();
          $("input[name=birthday]").val(year + "-" + month + "-" + day);
          $("form").eq(0).trigger("submit");
      })
  });
</script>

app/views/register/completed.erb
<p>仮登録の完了</p>
<a href="<%= register_main_index_path ({:id => @register.id, :token => @register.token}) %>">本登録URL</a>

app/views/register/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/register/error.html.erb
仮登録中ユーザーが見つかりませんでした｡

app/views/register/index.html.erb
<section>
  <div class="box">
    <h2>新規会員仮登録</h2>
    <p class="font12">
      アカウント本登録に関してのメールをお送りいたしますので、<br>
      メールアドレスをご入力ください。
    </p>
    <%= form_with :model => @register, :url => register_create_path, :method => "post", :html => {:"class" => "submit-form-to-temp" } do |form|%>
      <!-- email /////////////////////////////// -->
      <p>メールアドレス</p>
      <% if @register.errors.messages.length > 0 then %>
        <% @register.errors.messages[:email].each do |error|%>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <p><%= form.text_field :email %></p>
      <!-- display_name /////////////////////////////// -->
      <p>ニックネーム</p>
      <% if @register.errors.messages.length > 0 then %>
        <% @register.errors.messages[:display_name].each do |error|%>
          <p class="input_red"><%= error %></p>
        <% end %>
      <% end %>
      <p><%= form.text_field :display_name %></p>
      <!-- 性別 /////////////////////////////// -->
      <% if @register.errors.messages.length > 0 then %>
        <% @register.errors.messages[:gender].each do |error|%>
          <p class="input_red"><%= error %></p>
        <%end%>
      <%end%>
      <div class="selectors">
        <p>性別</p>
        <div class="cp_ipselect cp_sl04">
          <%= form.select :gender, @genders %>
        </div>
      </div>
      <div class="btnbox">
        <a id="submit-form" class="btn">登録</a>
      </div>
    <% end %>
  </div>
  <!--box-->
</section>
<script>
  $(function() {
      $("#submit-form").on("click", function (e) {
        $(".submit-form-to-temp").eq(0).trigger("submit")
      });
  });
</script>

app/views/register/main_index.html.erb
<h1>New Member</h1>
<%= render 'form', member: @member %>

app/views/register/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>