config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => "/cable"

  # TOPページ
  get "/", {
    :to => "top#index",
    :as => "top",
  }

  # ----------------------------------------------
  # api
  # ----------------------------------------------
  namespace "api" do

    # 画像を取り扱うAPI
    scope "image" do

      # ログインユーザーがアップ済みの画像一覧を取得する
      get "/list", {
        :to => "images#list",
        :as => "images_owner_has",
      }
      # 指定した異性ユーザーの全画像を取得する
      get "/list/:member_id", {
        :to => "images#member",
        :as => "images_selected_member_has",
      }
      # 画像表示用 URL(※所有者のみ閲覧可能)
      get "/:id/:member_id/:token_for_api", {
        :to => "images#owner_image_url",
        :as => "private_image",
      }
      # 画像表示用 URL(※第三者閲覧用)
      get "/:id/:token", {
        :to => "images#image_url",
        :as => "public_image",
      }
      # To upload any images.
      post "/update/:id", {
        :to => "images#update",
        :as => "image_update",
      }
      post "/delete/:id", {
        :to => "images#delete",
        :as => "image_delete",
      }
      post "/", {
        :to => "images#upload",
        :as => "image_upload",
      }
    end

    # メッセージ送信用
    scope "timeline" do
      get "/messages/:from_member_id/:to_member_id", {
        :to => "timelines#messages",
        :as => "timeline_messages",
      }
      post "/", {
        :to => "timelines#create_message",
        :as => "timeline_create_message",
      }
      post "/upload", {
        :to => "timelines#create_image",
        :as => "timeline_create_image",
      }
    end

    # API用ユーティリティー情報
    scope "utilities" do
      get "/get", {
        :to => "utilities#get",
        :as => "utilities_list",
      }
    end

    # メンバー情報を取得するためのAPI
    scope "member" do
      get "/:id", {
        :to => "member#show",
        :as => "member_show",
      }
    end
  end

  get "sessions/new"
  resources :logs
  resources :urls
  resources :declines
  # resources :images
  # resources :messages
  # resources :timelines
  resources :footprints
  # resources :likes
  # resources :members
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ----------------------------------------------
  # 通常のHTTPリクエスト
  # List notices to logged in user.
  # ----------------------------------------------
  get "/notices/", {
    :to => "notices#index",
    :as => "notices",
  }

  post "/images/active/:id", {
    :to => "images#active",
    :as => "active_image",
  }

  post "/images/deactive/:id", {
    :to => "images#deactive",
    :as => "deactive_image",
  }

  # ----------------------------------------------
  # メッセージ
  # ----------------------------------------------
  get "/messages/", {
    :to => "messages#index",
    :as => "messages",
  }
  get "/messages/:id", {
    :to => "messages#talk",
    :as => "message_talk",
  }
  post "/messages/create", {
    :to => "messages#create",
    :as => "message_create",
  }

  # ----------------------------------------------
  # いいねを贈る
  # ----------------------------------------------
  # 異性にいいねを贈る
  post "/like/send/:id", {
    :to => "likes#inform",
    :as => "inform_like",
  }
  # 贈ったいいねをキャンセル
  post "/like/cancel/:id", {
    :to => "likes#cancel",
    :as => "cancel_like",
  }

  # ----------------------------------------------
  # マイページ関連
  # ----------------------------------------------
  get "/mypage", {
    :to => "mypage#index",
    :as => "mypage",
  }
  get "/mypage/edit", { :to => "mypage#edit" }
  patch "/mypage/edit", { :to => "mypage#update" }
  # 画像のぼかし具合を設定
  post "/mypage/upload/:id", {
    :to => "mypage#update_image",
    :as => "mypage_update_image",
  }
  get "/mypage/upload", {
    :to => "mypage#upload",
  }
  post "/mypage/upload", { :to => "mypage#completed_uploading" }
  delete "/mypage/delete_image", {
    :to => "mypage#delete_image",
  }

  # 贈ったいいね
  get "/mypage/informing_likes", {
        :to => "mypage#informing_likes",
        :as => "mypage_informing_likes",
      }
  # もらったいいね
  get "/mypage/getting_likes", {
        :to => "mypage#getting_likes",
        :as => "mypage_getting_likes",
      }
  # マッチング中ユーザー一覧
  get "/mypage/matching", {
    :to => "mypage#matching",
    :as => "mypage_matching",
  }
  # ブロック中ユーザー一覧
  get "/mypage/blocking", {
    :to => "mypage#blocking",
    :as => "mypage_blocking",
  }
  # 足跡一覧
  get "/mypage/footprints", {
    :to => "mypage#footprints",
    :as => "mypage_footprints",
  }
  # # ログ一覧
  # get "/mypage/logs", {
  #   :to => "mypage#logs",
  #   :as => "mypage_logs",
  # }
  get "/mypage/logout", {
    :to => "mypage#logout",
    :as => "logout",
  }
  # ログイン中ユーザーが自身のプロフィール画面を閲覧する
  get "/mypage/profile", :to => "mypage#prfile", :as => "mypage_profile"

  # ----------------------------------------------
  # ログインページ
  # ----------------------------------------------
  scope "login", :as => :login do
    get "/", {
      :to => "sessions#new",
    }
    post "/", {
      :to => "sessions#create",
    }
  end

  # ----------------------------------------------
  # 新規登録時の仮登録
  # ----------------------------------------------
  scope("register", :as => :register) do
    post "/", {
      :to => "register#create",
      :as => "create",
    }
    get "/", {
      :to => "register#index",
      :as => "index",
    }
    get "/:id/:token", {
      :to => "register#main_index",
      :as => "main_index",
    }
    post "/:id/:token", {
      :to => "register#main_create",
      :as => "main_create",
    }
    get "/completed", {
      :to => "register#completed",
      :as => "completed",
    }
    get "/pre-completed", {
      :to => "register#completed",
      :as => "pre-completed",
    }
  end

  # ----------------------------------------------
  # メンバー情報関連
  # ----------------------------------------------
  scope "members", :as => :members do
    get "/search", {
      :to => "members#search",
      :as => "search",
    }
    get "/:id", {
      :to => "members#show",
      :as => "show",
    }
    get "/", {
      :to => "members#index",
      :as => "index",
    }
  end
end

app/views/common/_footer.html.erb
<% if (@current_user != nil) then%>
  <!-- ユーザーログイン中メニュー -->
  <div class="footer_menu">
    <div class="footer_menu_in">
      <div class="footer_menu_icon">
        <a href="<%= mypage_url() %>">
          <img src="/images/footer_menu1.png">
        </a>
        <span>マイページ</span>
      </div>
      <div class="footer_menu_icon">
        <% if @uncheck_messages != nil && @uncheck_messages.length > 0 %>
          <span class="pochi"><span class="pochi_in"></span></span>
        <% end %>
        <a href="<%= messages_url() %>"><img src="/images/footer_menu2.png"></a>
        <span>メッセージ</span>
      </div>
      <div class="footer_menu_icon">
        <% if @uncheck_notices != nil && @uncheck_notices.length > 0 then%>
          <span class="pochi"><span class="pochi_in"></span></span>
        <% end %>
        <a href="<%= notices_url %>"><img src="/images/footer_menu3.png"></a>
        <span>お知らせ</span>
      </div>
      <div class="footer_menu_icon">
        <% if @uncheck_footprints != nil && @uncheck_footprints.length > 0 %>
          <span class="pochi"><span class="pochi_in"></span></span>
        <% end %>
        <a href="<%= mypage_footprints_url() %>"><img src="/images/footer_menu4.png"></a>
        <span>足跡</span>
      </div>
    </div>
  </div>
  <!--footer_menu-->
<% end %>
<footer>
</footer>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script type="text/javascript">
  $(document).ready(function() {
      $(".drawer").drawer();
  });
  $(".backk").on("click", function (e) {
      e.preventDefault();
      history.back();
  });
  $(".button_to_back_previous_page").on("click", function (e) {
      e.preventDefault();
      history.back();
  })
</script>
</body>
</html>

app/views/common/_header.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">
    <title><%= @title%></title>
    <meta name="keywords" content="<%= @keywords %>">
    <meta name="description" content="<%= @description %>">
    <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1,viewport-fit=cover">
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="" />
    <!-- ここからOGP -->
    <meta property="og:title" content="">
    <meta property="og:type" content="article">
    <meta property="og:description" content="">
    <meta property="og:url" content="" />
    <meta property="og:image" content="" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosansjp.css">
    <link rel="stylesheet" href="https://use.typekit.net/nki7ezk.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="/css/slick-theme.css" />
    <link rel="stylesheet" type="text/css" href="/css/drawer.css">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <link rel="apple-touch-icon" href="/img/favicon.ico">
    <link rel="canonical" href="">
    <script src="/js/jquery-3.5.1.min.js"></script>
    <script src="/js/iscroll.min.js"></script>
    <script src="/js/drawer.min.js"></script>
    <script src="/js/slick.js" type="text/javascript"></script>
    <script src="/js/axios.min.js"></script>
    <script src="/js/vue@2.6.12.js"></script>
    <script src="/js/vue-carousel.min.js"></script>
  </head>
  <body class="drawer drawer--right">
    <button type="button" class="drawer-toggle drawer-hamburger">
      <!--変更予定-->
      <span class="sr-only">toggle navigation</span>
      <span class="drawer-hamburger-icon"></span>
    </button>
    <% if @current_user != nil then %>
      <nav class="drawer-nav">
        <div class="side_profile">
          <div class="side_profile1">
            <div class="side_profile1a">
              <a href="" class="side_profile1b">
                <img src="/images/sample_user.jpg">
              </a>
            </div>
            <a href="" class="side_profile1b"><%= @current_user.display_name %></a>
          </div>
          <!--side_profile1-->
          <div class="side_profile2">
            <a href="<%= mypage_getting_likes_url() %>" class="side_profile2b"><%= @current_user.getting_likes.valid_likes(@current_user).length %> もらったLIKE</a>
            <a href="<%= mypage_informing_likes_url() %>" class="side_profile2a"><%= @current_user.informing_likes.valid_likes(@current_user).length %> 贈ったLIKE</a>
            <a href="<%= mypage_matching_url() %>" class="side_profile2a"><%= @current_user.informing_likes.length %> 相互LIKE</a>
          </div>
          <!--side_profile2-->
        </div>
        <!--side_profile-->
        <ul class="drawer-menu">
          <li><a href="<%= members_search_url() %>">条件検索</a></li>
          <li><a href="">メッセージ</a></li>
          <li><a href="<%= mypage_footprints_url() %>">足跡</a></li>
          <li><a href="<%= notices_url() %>">お知らせ</a></li>
          <li><a href="<%= mypage_edit_url() %>">プロフィール編集</a></li>
          <li><a href="">有料プラン新規･変更</a></li>
          <li><a href="">設定</a></li>
          <li><a href="<%= mypage_blocking_url() %>">ブロック一覧</a></li>
          <li><a href="<%= logout_url() %>">ログアウト</a></li>
          <span class="sub_line"></span>
          <li class="mini"></li>
          <li class="mini"><img src="/images/checkicon.png" width="12"> 本人確認済</li>
          <li class="mini"><a href="{{action("Member\\IndexController@identity")}}"><img src="/images/caitionicon.png" width="12"> 本人確認証明書アップロード</a></li>
          <!-- 収入両名は男性のみ対応 -->
          <li class="mini"><img src="/images/checkicon.png" width="12"> 収入証明確認済</li>
          <li class="mini"><a href="{{action("Member\\IndexController@income")}}"><img src="/images/caitionicon.png" width="12"> 収入証明アップロード</a></li>
        </ul>
      </nav>
    <% else %>
      <nav class="drawer-nav">
        <ul class="drawer-menu">
          <li><a href="<%= login_url() %>">ログイン</a></li>
          <li><a href="<%= register_index_url() %>">新規会員登録</a></li>
          <span class="sub_line"></span>
          <li><a href="/terms">会員規約</a></li>
          <li><a href="/info">特定商取引法に基づく表記</a></li>
          <li><a href="/privacy">プライバシーポリシー</a></li>
        </ul>
      </nav>
    <% end %>
    <header>
      <!-- <a href=""><img src="/images/ttl.png" width="100"></a> -->
    </header>